# Generated by Django 5.0.2 on 2024-02-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=3, unique=True, verbose_name='Буквенный код')),
                ('valuta_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID валюты')),
                ('numcode', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цифровой код')),
                ('nominal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Единиц')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ('charcode',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата установки курса')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс валюты в рублях')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.currency', verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('date',),
            },
        ),
    ]
